# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-20 12:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='related_items',
            field=models.ManyToManyField(blank=True, to='store.Item'),
        ),
    ]
