# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-20 12:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20171020_1256'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image',
            field=models.ImageField(default=None, upload_to=''),
        ),
    ]
