# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-20 13:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20171020_1300'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='amount_left',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
